services:
    postgres:
        image: postgres:latest
        container_name: $POSTGRES_HOST
        environment:
            POSTGRES_DB: $POSTGRES_DATABASE
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_HOST: $POSTGRES_HOST
            POSTGRES_PORT: 5432
        env_file:
            - .env
        volumes:
            - /tmp/os-pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - osnetwork
        restart: always
networks:
    osnetwork:
        driver: bridge
